name: Validate C4Script functions

on:
  push:
    branches: [ 'master' ]

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: .github/workflows/C4ScriptDocAnalyzer/package-lock.json
      - run: npm install
      - name: Build function list
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends xsltproc python-libxml2 gettext -y
          git clone https://github.com/legacyclonk/lcdocs --depth 1
          make -C lcdocs -j$(nproc)
          cp lcdocs/Functions.txt .github/workflows/C4ScriptDocAnalyzer/lcdocs_functions.txt
      - name: Run analyze script
        id: analyze
        run: node .github/workflows/C4ScriptDocAnalyzer/index.js
        continue-on-error: false

