name: Validate C4Script functions

on:
  push:
    #branches: [ 'master']

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout LegacyClonk repo
        uses: actions/checkout@v3

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          #repository: legacyclonk/lcdocs
          repository: Somebodyisnobody/lcdocs
          ref: schema-validation
          path: lcdocs

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: .github/workflows/C4ScriptDocAnalyzer/package-lock.json

      - name: Install dependencies
        run: |
          npm install --prefix .github/workflows/C4ScriptDocAnalyzer/

      - name: Build function list
        run: make -C lcdocs lcdocs_summary.json -j$(nproc)

      - name: Copy generated lcdocs_summary.json
        run: cp lcdocs/lcdocs_summary.json .github/workflows/C4ScriptDocAnalyzer/lcdocs_summary.json

      - name: Run analyze script
        id: analyze
        run: node .github/workflows/C4ScriptDocAnalyzer/index.js
        continue-on-error: false

